// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/params.dart';
import '../utils/result.dart';
import '../utils/return_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'statement.dart';
import 'transaction.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Connection>>
abstract class Connection implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Database>>
abstract class Database implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibsqlConnection>>
abstract class LibsqlConnection implements RustOpaqueInterface {
  Connection get connection;

  Database get database;

  set connection(Connection connection);

  set database(Database database);

  Future<void> batch({required String sql});

  Future<void> disableExtension();

  Future<void> enableExtension();

  Future<ExecuteResult> execute(
      {required String sql, LibsqlParams? parameters});

  Future<void> loadExtension({required String path, String? entryPoint});

  Future<LibsqlStatement> prepare({required String sql});

  Future<QueryResult> query({required String sql, LibsqlParams? parameters});

  Future<void> sync_();

  Future<LibsqlTransaction> transaction({LibsqlTransactionBehavior? behavior});
}
