// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/params.dart';
import '../utils/result.dart';
import '../utils/return_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibsqlStatement>>
abstract class LibsqlStatement implements RustOpaqueInterface {
  Statement get statement;

  set statement(Statement statement);

  Future<ExecuteResult> execute({LibsqlParams? parameters});

  Future<void> finalize();

  Future<QueryResult> query({LibsqlParams? parameters});

  Future<void> reset();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Statement>>
abstract class Statement implements RustOpaqueInterface {}
