// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/params.dart';
import '../utils/result.dart';
import '../utils/return_value.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LibsqlTransaction>>
abstract class LibsqlTransaction implements RustOpaqueInterface {
  Transaction get transaction;

  set transaction(Transaction transaction);

  Future<void> commit();

  Future<ExecuteResult> execute(
      {required String sql, LibsqlParams? parameters});

  Future<QueryResult> query({required String sql, LibsqlParams? parameters});

  Future<void> rollback();
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transaction>>
abstract class Transaction implements RustOpaqueInterface {}

enum LibsqlTransactionBehavior {
  deferred_,
  immediate,
  exclusive,
  readOnly,
  ;
}
